[package]
name = "webrtc-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.39", features=["derive"]}
mainline = "5.4.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
webrtc = "0.13.0"
